### ISSUE TITLE
Promises & Await - Write better async code in Swift

### ISSUE THREAD

**Issue by Morbix** [OpenCraft/Whiteboard#27]
https://github.com/malcommac/Hydra

**Comment by luis-silva-ilegra** [comment]
I'll present this Friday the 24th

**Comment by Morbix** [comment]
https://www.youtube.com/watch?v=vWSNHKeR5AM&list=PLWOTHYZo_P_CyEDzvJNe1LXcJTcnKXwHz&index=6&t=642s
